### ISSUE TITLE
Distribute via F-Droid

### ISSUE THREAD

**Issue by haeckle** [flocke/andOTP#1]
Would be really nice for getting automatic updates without relying on Google Play.

https://f-droid.org/

**Comment by flocke** [comment]
I'm gonna look into how to submit it to F-Droid in the next time.
I just looked over the dependencies I use and there shouldn't be any problems on the license side.

**Comment by flocke** [comment]
After trying to set up the F-Droid buildserver a couple of times and failing I just submitted it here:
https://gitlab.com/fdroid/rfp/issues/260

I will keep this Issue open until it is accepted.

**Comment by flocke** [comment]
The submission has been accepted and the app should appear in the F-Droid store in a few days.

**Comment by haeckle** [comment]
Wow, that was quick. Thanks a lot!

**Comment by flocke** [comment]
Yeah, that was mostly thanks to the guys at F-Droid.
I submitted my request and it didn't even take a full day for them to add it.

**Comment by flocke** [comment]
It seems to be online in the F-Droid client now.

_Sent from my Google Nexus 5X using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_
