### ISSUE TITLE
Add a way to sort the entries

### ISSUE THREAD

**Issue by alphazo** [flocke/andOTP#12]
Just migrated from freeOTP to andOTP. I like the support for fingerprint authentication and also import/export functions.
I have quite a number of entries in my list and would find very usefully to have an option to sort the entries based upon the label.

**Comment by flocke** [comment]
If you want your entries to be permanently sorted you can manually do that via drag and drop, those changes will be saved.
If you want a temporary (lost on restart of the app) sort method that sorts by label I will look into that.

_Sent from my Google Nexus 5X using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by flocke** [comment]
I've implemented a basic function to sort the entries by label.
My question: should the sort methode (by label or unsorted) be saved?
As it is now it is reset to unsorted every time the app is restarted.

**Comment by alphazo** [comment]
IMHO, the list order should not be reset when you restart the app, once it has been sorted either manually or using the sort button. Maybe a reset button or a dual mode sort button that once toggled can revert the list back to unsorted.

**Comment by alphazo** [comment]
It would be nice if the mode could be remembered and thus even for the "unsorted" one. Maybe there should be a visual information to indicate the current active mode.

**Comment by flocke** [comment]
Done, now the sort mode is remembered when the app is closed.
This all will be in the next release.
