### ISSUE TITLE
Option to disable swipe to delete

### ISSUE THREAD

**Issue by alphazo** [flocke/andOTP#13]
## Help wanted: Please see the first comment and tell me your opinion.

While swiping is quite useful in applications like emails it may not be so much of a daily use in an application like andOTP that deals with pretty static entries. I mean have cliking on the three dots to remove an entry is enough.
I find the swipe quite dangerous since it doesn't remind the name of the entry to be removed in the confirmation pop-up. It would be nice to have an option to completely disable such swiping feature and avoid unexpected removal.

**Comment by flocke** [comment]
Question to the other users: Should this be an option or should I just completely disable it?
I just implemented it because the tutorial I took the drag & drop code from also contained swipe to dismiss. Maybe the Remove option in the three dot menu is enough.

**Comment by d4v3k** [comment]
I would like the swipe feature removed. It's like @alphazo said, it's kind of dangerous and clicking on the three dots seems to be enough.

**Comment by Datenschutz** [comment]
Completely drop it, the three dot removal way is almost as fast and as said earlier, it's pretty risky.

**Comment by flocke** [comment]
I'm gonna leave this issue open till Monday and decide then, leaving more users the time to comment.

_Sent from my Google Nexus 5X using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by azlux** [comment]
Yes, it's dangerous, you need at least a big popup to confirm, but a menu to delete on entry  is better I think.

**Comment by jerryn70** [comment]
Swipe is dangerous.

**Comment by flocke** [comment]
Ok, this seems pretty clear. I'm gonna remove swipe permanently.
