### ISSUE TITLE
Cannot scroll on the backup page

### ISSUE THREAD

**Issue by nebulon42** [flocke/andOTP#15]
On my device there is no scroll bar on the backup page. So I'm not able to see all options.
LineageOS 14.1 (Android 7.1.2)

**Comment by flocke** [comment]
I always had everything on one page on my test device so I never encountered that problem.
Will look into it as soon as I can.

_Sent from my Google Nexus 5X using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_
