### ISSUE TITLE
Copy Token when clicking on the item instead of clicking on the clipboard icon

### ISSUE THREAD

**Issue by jerryn70** [flocke/andOTP#17]
Currently we need to click the clipboard icon to copy the Token. For easy copying Clicking on the entry to copy is good. Like freeOTP app

**Comment by flocke** [comment]
Do you mean when clicking on the whole card or on the token display? Because the whole card is already reserved for tap to reveal.

_Sent from my Google Nexus 5X using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by jerryn70** [comment]
I mean clicking on the whole card. But that will affect tab to reveal.

**Comment by flocke** [comment]
I'm actually currently considering to move the copy function to the three-dot menu to save space on the card.
If I implement HOTP support I have to display the counter in addition to all the other stuff so we may run into a space problem when displaying all this information.

_Sent from my Google Nexus 5X using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by jerryn70** [comment]
Moving copy button to the 3 bot menu is more difficult for user to copy Tokens. 
That affects the simplicity of this app .


My suggestion is to remove tap to reveal by tap to copy token. Or keep the current copying method.

**Comment by Datenschutz** [comment]
@jerryn70 is right there - imagine logging into an online account and always going into the submenu.. tapping the card might actually be better then what I sugessted in #10. It's also the default behaviour of FreeOTP, which is nice for users that switch.

**Comment by flocke** [comment]
For now I like the way it is implemented. I don't really see a need to remove the copy button and drop the tap to reveal function for this. It's not really that difficult to hit the copy button instead of just somewhere on the card.
I will leave it as it is right now, if I encounter space problems during the implementation of HOTP in the future I will revisit the idea.
