### ISSUE TITLE
Possibility to change label font size

### ISSUE THREAD

**Issue by reedcourty** [flocke/andOTP#18]
If the font size of entry labels could be adjustable then the whole entry would be readable.

**Comment by flocke** [comment]
That sounds easily doable, I could also make the label scroll horizontally if its too long.

_Sent from my Google Nexus 5X using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by ort163** [comment]
In Nougat, the label does not scroll? I am having lineageOS and scanned Google-QR code for gmail account? I can provide screenshot

**Comment by flocke** [comment]
I haven't added the scrolling functionality yet. I didn't think it was necessary to have both, the label size configurable and the scrolling text.
But if you want I can still add it.
