### ISSUE TITLE
FYI: I wrote a script to decrypt password-protected backups

### ISSUE THREAD

**Issue by asmw** [flocke/andOTP#19]
Maybe useful to you or other users:
https://github.com/asmw/andOTP-decrypt

I guess this could also be extended to create valid import files.

**Comment by Datenschutz** [comment]
Great! You might wanna add that to the Readme or something. @asmw Would you mind to add a QR-Code generation?

**Comment by asmw** [comment]
@Datenschutz eh, why not :)

**Comment by asmw** [comment]
There you go.

**Comment by flocke** [comment]
Thanks for the script @asmw ! I was planing to write something similar myself but you were faster ;)
I will add it to the README of andOTP as soon as I can.

**Comment by Datenschutz** [comment]
Awesome! Great to see! @flocke maybe add a little note on the backup page? Seems fitting

**Comment by asmw** [comment]
Another FYI: I wrote this for myself, so someone else should probably review/test this for usability and if the docs are sufficient

**Comment by flocke** [comment]
@asmw I'm not gonna add it on the Backup menu in the app but I'm gonna drop a link to the GitHub repo in the README of andOTP. If you want I can add some hint like "(needs more testing)" to the link.

**Comment by asmw** [comment]
Good for me. Thanks for your work!
