### ISSUE TITLE
Import FreeOTP tokens.xml file

### ISSUE THREAD

**Issue by pejakm** [flocke/andOTP#2]
How can I import my codes from [FreeOTP](https://github.com/freeotp/freeotp-android)? They are stored in a xml file, entries look like this:

```
<?xml version='1.0' encoding='utf-8' standalone='yes' ?>
<map>
    <string name="example@example:Example">{&quot;algo&quot;:&quot;SHA1&quot;,&quot;counter&quot;:0,&quot;digits&quot;:6,&quot;issuerExt&quot;:&quot;example@example&quot;,&quot;label&quot;:&quot;Example&quot;,&quot;period&quot;:30,&quot;secret&quot;:[98,-92,-87,46,76,-1,117],&quot;type&quot;:&quot;TOTP&quot;}</string>
    <string name="tokenOrder">[&quot;example@example:Example&quot;]</string>
</map>
```

**Comment by pejakm** [comment]
I have tried this tool: http://tomeko.net/online_tools/base32.php?lang=en to convert FreeOTP's secret to hex and then entering it into andOTP, but it didn't reproduce the same code.

**Comment by flocke** [comment]
I have never used FreeOTP myself and I am currently not at home, but as soon as I return I will have a look.

**Comment by flocke** [comment]
Could you upload an XML file with an example account for me?

_Sent from my Google Nexus 5X using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by Datenschutz** [comment]
Using https://github.com/minus7/freeotp-export/blob/master/freeotp-export.py works for me, if you remove the part that's responsible for extracting the xml.  
There is also https://github.com/viljoviitanen/freeotp-export/blob/master/export.html which is in JS, that may be easier to implement. Those scripts convert FreeOTPs tokens.xml into a [usable format](https://github.com/google/google-authenticator/wiki/Key-Uri-Format).
The tokens.xml looks exactly as @pejakm pasted it.

**Comment by flocke** [comment]
I'm not sure yet if I want to add the option to import other formats to andOTP since I want to keep the app itself light.
A simple (online) solution that converts freeotp XML files to (encrypted) andOTP backup files would be the best in my opinion.

**Comment by pejakm** [comment]
> Could you upload an XML file with an example account for me?

Sorry, I missed this. First post contains example, just save it as tokens.xml.

**Comment by pejakm** [comment]
I have managed to import my FreeOTP data to andOTP, thanks!

**Comment by Datenschutz** [comment]
So it might be worth more to get a script / local HTML file with JavaScript which can generate QR-Codes or the secrets from the strings.xml, didn't find something there

**Comment by flocke** [comment]
It would be nice if someone else could write a HTML/JavaScript approach to generate QR-Codes from the FreeOTP XML files.
I am not really familiar with HTML or Javascript ...

**Comment by flocke** [comment]
I submitted a pull request to https://github.com/viljoviitanen/freeotp-export adding a JavaScript file to export the tokens.xml file and generate QR codes from it.
As soon as it is merged I will close this issue and add it to the README file.
