### ISSUE TITLE
OpenPGP with OpenKeychain and security token

### ISSUE THREAD

**Issue by carmebar** [flocke/andOTP#20]
Using OpenKeychain with a security token ends up in an infinite loop.

OpenKeychain prompt says it has finished succesfully and then then it asks again to put the token near the device.
Using another key that doesn't require security token works as expected.

Tested on 0.2.3(F-Droid) and 0.2.4(Google Play)

Thank you for keeping this awesome project alive 😄

**Comment by flocke** [comment]
Let me check out the code when I get home if I can find some obvious bugs that could cause this.
I don't own a security token myself, would you be willing to test builds and send me logcats of there is an error?
Could you already post a logcat of the current version?

_Sent from my Google Nexus 5X using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by carmebar** [comment]
Sure, I'll help you with the troubleshooting.

org.shadowice.flocke.andotp doesn't output anything relevant during the loop:

> $ adb logcat | grep -F "`adb shell ps | grep org.shadowice.flocke.andotp | cut -c10-15`"
> 08-02 14:30:09.764   866   879 I ActivityManager: Start proc 32131:org.shadowice.flocke.andotp/u0a141 for activity org.shadowice.flocke.andotp/.MainActivity
> 08-02 14:30:09.819 32131 32131 I art     : Starting a blocking GC AddRemoveAppImageSpace
> 08-02 14:30:09.822 32131 32131 W System  : ClassLoader referenced unknown path: /data/app/org.shadowice.flocke.andotp-1/lib/arm
> 08-02 14:30:10.232 32131 32157 I Adreno-EGL: <qeglDrvAPI_eglInitialize:379>: QUALCOMM Build: 10/21/15, 369a2ea, I96aee987eb
> 08-02 14:30:10.235 32131 32157 I OpenGLRenderer: Initialized EGL, version 1.4
> 08-02 14:30:10.235 32131 32157 D OpenGLRenderer: Swap behavior 1
> 08-02 14:31:57.709 32131 32131 W art     : Before Android 4.1, method int android.support.v7.widget.ListViewCompat.lookForSelectablePosition(int, boolean) would have incorrectly overridden the package-private method in android.widget.ListView
> 08-02 14:31:59.193 32131 32157 D OpenGLRenderer: endAllActiveAnimators on 0x99edfd80 (MenuPopupWindow$MenuDropDownListView) with handle 0x9aad3970
> 08-02 14:32:03.920 32131 32157 D OpenGLRenderer: endAllActiveAnimators on 0x98b61b00 (RippleDrawable) with handle 0x9aad3410
> ^C

**Comment by flocke** [comment]
Alright, doesn't look to useful ;)
Tomorrow I'm gonna add some debug messages in the OpenPGP part and upload a build for you to test.

_Sent from my Google Nexus 5X using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by flocke** [comment]
You grep-ed for andOTP in your logcat, could you try OpenKeychain as well? Maybe they have some useful information.

_Sent from my Google Nexus 5X using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by carmebar** [comment]
Updated logcat adding OpenKeychain output:

> $ adb logcat | grep -F "\`adb shell ps | egrep 'org.shadowice.flocke.andotp|org.sufficientlysecure.keychain' | cut -c10-15\`"
> 08-02 18:14:36.052  2606  2606 I art     : Starting a blocking GC AddRemoveAppImageSpace
> 08-02 18:14:36.055  2606  2606 W System  : ClassLoader referenced unknown path: /data/app/org.shadowice.flocke.andotp-1/lib/arm
> 08-02 18:14:36.519  2606  2631 I Adreno-EGL: <qeglDrvAPI_eglInitialize:379>: QUALCOMM Build: 10/21/15, 369a2ea, I96aee987eb
> 08-02 18:14:36.528  2606  2631 I OpenGLRenderer: Initialized EGL, version 1.4
> 08-02 18:14:36.528  2606  2631 D OpenGLRenderer: Swap behavior 1
> 08-02 18:14:39.284  2606  2631 I Adreno-EGL: <qeglDrvAPI_eglInitialize:379>: QUALCOMM Build: 10/21/15, 369a2ea, I96aee987eb
> 08-02 18:14:39.284  2606  2631 I OpenGLRenderer: Initialized EGL, version 1.4
> 08-02 18:14:39.285  2606  2631 D OpenGLRenderer: Swap behavior 1
> 08-02 18:14:43.309  2687  2687 I art     : Starting a blocking GC AddRemoveAppImageSpace
> 08-02 18:14:43.313  2687  2687 W System  : ClassLoader referenced unknown path: /data/app/org.sufficientlysecure.keychain-1/lib/arm
> 08-02 18:14:43.877  2723  2723 I art     : Starting a blocking GC AddRemoveAppImageSpace
> 08-02 18:14:43.881  2723  2723 W System  : ClassLoader referenced unknown path: /data/app/org.sufficientlysecure.keychain-1/lib/arm
> 08-02 18:14:43.965  2687  2740 I Adreno-EGL: <qeglDrvAPI_eglInitialize:379>: QUALCOMM Build: 10/21/15, 369a2ea, I96aee987eb
> 08-02 18:14:43.968  2687  2740 I OpenGLRenderer: Initialized EGL, version 1.4
> 08-02 18:14:43.968  2687  2740 D OpenGLRenderer: Swap behavior 1
> 08-02 18:14:59.216  2606  2631 I Adreno-EGL: <qeglDrvAPI_eglInitialize:379>: QUALCOMM Build: 10/21/15, 369a2ea, I96aee987eb
> 08-02 18:14:59.216  2606  2631 I OpenGLRenderer: Initialized EGL, version 1.4
> 08-02 18:14:59.216  2606  2631 D OpenGLRenderer: Swap behavior 1
> 08-02 18:15:02.584  2606  2606 W art     : Before Android 4.1, method int android.support.v7.widget.ListViewCompat.lookForSelectablePosition(int, boolean) would have incorrectly overridden the package-private method in android.widget.ListView
> 08-02 18:15:04.119  2606  2631 D OpenGLRenderer: endAllActiveAnimators on 0x99ec0f80 (MenuPopupWindow$MenuDropDownListView) with handle 0x9abfc430
> 08-02 18:15:06.908  2606  2631 D OpenGLRenderer: endAllActiveAnimators on 0x97fc2080 (RippleDrawable) with handle 0x9abfc4d0
> 08-02 18:15:14.474  2687  2740 D OpenGLRenderer: endAllActiveAnimators on 0x98e5b780 (RippleDrawable) with handle 0x9997d1d0
> 08-02 18:15:14.601  2687  2687 W IInputConnectionWrapper: finishComposingText on inactive InputConnection
> 08-02 18:15:14.601  2687  2687 W IInputConnectionWrapper: finishComposingText on inactive InputConnection
> 08-02 18:15:37.364  2687  2740 D OpenGLRenderer: endAllActiveAnimators on 0xacfe6f00 (RippleDrawable) with handle 0x997c1120
> 08-02 18:15:37.698  2606  2631 D OpenGLRenderer: endAllActiveAnimators on 0x97fc2400 (RippleDrawable) with handle 0x9abfc7a0
> ^C

Here are the ps output:
> $ adb shell ps | egrep 'org.shadowice.flocke.andotp|org.sufficientlysecure.keychain'
> u0_a141   2606  281   1003748 52168 sys_epoll_ 00000000 S org.shadowice.flocke.andotp
> u0_a140   2687  281   1022140 66216 sys_epoll_ 00000000 S org.sufficientlysecure.keychain
> u0_a140   2723  281   996144 41012 sys_epoll_ 00000000 S org.sufficientlysecure.keychain:sync

Maybe during the weekend I'll have some time to debug myself the PGP backup code.

**Comment by carmebar** [comment]
Seems the bug is not with andOTP but with OpenKeyChains. Conversations seems to have the same problem:
https://github.com/siacs/Conversations/issues/957

**Comment by carmebar** [comment]
I've found out that you're supposed to send the old intent.
I've created a Pull Request: https://github.com/flocke/andOTP/pull/25

Not sure if that's the way you'd want to fix it but that version works as expected with my Yubikey NEO.

**Comment by flocke** [comment]
Let me look into it, but as long as it fixes your issue and doesn't break anything else I'm not against merging it.

**Comment by flocke** [comment]
Should be fixed with your pull request.
