### ISSUE TITLE
Feature request: allow more Hash Algorithms

### ISSUE THREAD

**Issue by j0hnnybash** [flocke/andOTP#24]
Hi,
seems there´s a hardcoded hash algorithm (sha1).
in redhats FreeOTP (also on F-Droid) for example you can choose between md5, sha1, sha256, sha512.

I´m trying to avoid changing the algorithm on our companys OTP server :)

**Comment by flocke** [comment]
This should be easy enough to do.

**Comment by flocke** [comment]
I'm going to add SHA-256 and SHA-512, those are the only two other algorithms specified in the TOTP RFC: https://tools.ietf.org/html/rfc6238
MD5 is not mentioned there so I won't implement it (see also: https://mattrubin.me/2013/12/14/md5-otps.html)
