### ISSUE TITLE
Dark theme

### ISSUE THREAD

**Issue by cobraguy** [flocke/andOTP#3]
I really love dark themes and enable them on every app that offers them. Right now I'm using Google Authenticator for its dark theme but I much prefer this app because it lets you backup your keys in a simple JSON or encrypted format.

**Comment by flocke** [comment]
I will look into how to best implement this.
andOTP is my first Android app so I have to research a bit first ;)

**Comment by flocke** [comment]
It needs some more tweaks but the dark theme is working, it will be included in the next release.

_Sent from my Google Nexus 5X using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by cobraguy** [comment]
Awesome! Thanks for being so quick about it. :)

**Comment by flocke** [comment]
Ok, I spoke to soon ... there are still some things I have to work out for the theme to work.
I will postpone it until the next release.

**Comment by flocke** [comment]
Would you guys mind if I remove the icons in tap-to-reveal (the little eye and the crossed out eye). They are harder to style than I thought (well for everything below Lollipop).

_Sent from my Google Nexus 5X using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_
