### ISSUE TITLE
OTP list empty on Android O

### ISSUE THREAD

**Issue by alphazo** [flocke/andOTP#34]
#### General information

* App version: 0.2.5
* App source: F-Droid
* Android Version: Android O 8.0

#### Expected result

OTP list remains empty after restoring the app from a TitaniumBackup or restoring a previous backup using the built-in backup feature. When restoring a JSON backup, app states that import has been successfull. Tried to clear cache as well but that didn't help.

**Comment by flocke** [comment]
@alphazo  Could you upload a logcat? This could be the same error as #16

**Comment by flocke** [comment]
I'm gonna set up an Android O virtual phone tomorrow and check it out myself.

**Comment by alphazo** [comment]
More progress (Nexus5X).
- TitaniumBackup Restore (App+Data) :  Empty list
- TitaniumBackup Restore (App+Data) + andOTP JSON restore :  Empty list
- All the above then data erase + andOTP JSON restore : list is back ;)
- andOTP uninstalled then re-installed + TitaniumBakup restore (data only): Empty list
- andOTP uninstalled then re-installed + andOTP JSON restore : list is back ;)

There is a crypto related exception in the logcat: [logcat_and_device_info.zip](https://github.com/flocke/andOTP/files/1243239/logcat_and_device_info.zip)


PS: andOTP is not the only app I had issue with. Waze for expample kept FC until I fully erased app data.

**Comment by flocke** [comment]
Yes, this is to be expected. See the "Backups" section of the README on GitHub.
Titanium Backup only saves the encrypted data files, but to decrypt them a key is needed which is stored in the Android KeyStore. This key can not be backed up, so you can only use the internal backup function and not Titanium.

I think I read somewhere that Waze also uses the KeyStore, so it's probably the same problem there.

_Sent from my Google Nexus 5X using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by alphazo** [comment]
Good to hear there is an explanation. At least I had a recent in-application backup handy ;)

**Comment by flocke** [comment]
After looking at your logcat I'm 99% sure that is exactly whats happening.
I will close this report, just open a new one if there is something else strange happening on Android O.
