### ISSUE TITLE
Make destructive Panic trigger opt-in

### ISSUE THREAD

**Issue by digitalcircuit** [flocke/andOTP#35]
## In short

* Change PanicKit wipe data response to opt-in rather than always-on
  * Recommended by [Guardian Project's design patterns](https://guardianproject.info/2016/01/12/panickit-making-your-whole-phone-respond-to-a-panic-button/ )
  * Avoids unexpectedly losing tokens if using an 'anxious trigger' instead of panic
  * Allows choosing to keep OTP while using a panic trigger for other apps
  * Requires a new settings activity, possibly modeled after [Zom with multiple destructive responses and a default lock response](https://github.com/zom/Zom-Android/blob/master/app/src/main/java/org/awesomeapp/messenger/ui/PanicSetupActivity.java )

Criteria | Rank | Reason
---------|---------|-------------
Impact | ★★☆ *2/3* | User-facing but niche, matches other Panic-enabled apps
Risk | ★★☆ *2/3* | Changes default, should be noted in changelog
Intrusiveness | ★★☆ *2/3* | New UI page, new strings, mostly independent

*This would build upon the excellent work in [pull request #27](https://github.com/flocke/andOTP/pull/27 ).*

---

#### General information

* **App version:** [0.2.6](https://github.com/flocke/andOTP/releases/tag/v0.2.6 )
* **App source:** GitHub
* **Android Version:** *N/A*

#### Expected result
**What is expected?** 
On triggering the Panic button, nothing happens by default.

The panic settings must be manually configured to enable wiping OTP data.

**What does happen instead?**

On triggering the Panic button, OTP data is wiped without any opt-out.

#### Logcat
```
[Not recorded, but if needed I can set up the Android emulator to test this]
```

#### Steps to reproduce
 
 * Install and set up andOTP
 * Install some form of panic-button app, e.g. [Ripple](https://play.google.com/store/apps/details?id=info.guardianproject.ripple )
 * Check the panic app configuration for an Edit option
 * Try triggering a panic

**Comment by flocke** [comment]
And done. Was easier than I expected 👍
