### ISSUE TITLE
Feature request: tabs for grouping

### ISSUE THREAD

**Issue by SkyWheel** [flocke/andOTP#37]
Hi!
I have more than 20 OTPs, and it's really hard sometimes to search required one.
What if OTPs could be grouped by tab?
I.e. mail tab: and all OTPs for all mails, then work tab: and all OTPs for work.
Thank you.

**Comment by flocke** [comment]
I'm currently on vacation so I will have a look once I get back.
This seems like a big change, so I will have to decide if I want to implement it (I want to keep andOTP as simple/light as possible).

**Comment by flocke** [comment]
I don't really like the idea of tabs tbh. What do you think about adding (multiple) tags to an entry and the ability to filter the list by tag?

**Comment by SkyWheel** [comment]
I reckon it is not bad idea. I didn't think about that in this way. Anyway, to be able to sort somehow all those OTPs, is much better than nothing.
But may I ask you to implement tags' sorting remembering? So, we could have quick access to most frequently used OTPs after each andOTP openning.
And thank you for your work!

**Comment by RichyHBM** [comment]
I'm currently working on this, hopefully should have a pull request done this weekend

**Comment by flocke** [comment]
@RichyHBM Do you plan to implement tabs or tags? And thank you for your contributions!

**Comment by RichyHBM** [comment]
Sorry, I should have been clearer @flocke, I am doing TAGS. The way I currently have it you can add tags (either new ones or already existing ones) when adding a new entry manually, you can also modify the tags of existing entries. The app then has a drawer that lets you filter based on existing tags, the way I have defined an existing tag is just for it to be assigned to an entry.

I do have a question about the actual implementation of it, but I will ask that when I do the PR

**Comment by flocke** [comment]
Just some small teasers ...
Big thanks to @RichyHBM for doing most of the work to get this running.

![screenshot_20171117-134810](https://user-images.githubusercontent.com/76665/32948159-9cf85dc8-cb9e-11e7-8b62-77af7a276a3c.png)
![screenshot_20171117-134816](https://user-images.githubusercontent.com/76665/32948168-a2db8d14-cb9e-11e7-83e3-65316d0928ad.png)
