### ISSUE TITLE
Feature request: Steam mobile authenticator codes

### ISSUE THREAD

**Issue by Roliga** [flocke/andOTP#38]
Hi,

The [Steam Mobile Authenticator](https://support.steampowered.com/kb_article.php?ref=4440-RTUI-9218) uses standard TOTP passwords, but differs in that it generates a 5 character string. Is this something that could be implemented in andOTP?

For reference WinAuth has this implemented [here](https://github.com/winauth/winauth/blob/master/Authenticator/SteamAuthenticator.cs), see [this](https://winauth.com/2015/06/11/steam-guard-mobile/) for a short write up about it. The KeeTrayTOTP plugin for KeePass2 has a somewhat more concise implementation [here](https://github.com/victor-rds/KeeTrayTOTP/blob/b122a8b568e7f6770cda2770f854b1424ebaf865/Libraries/TOTPEncoder.cs).

Would be convenient with one less authenticator app on ones phone :)

**Comment by flocke** [comment]
The newest version of andOTP should support variable digit lengths.
I'm currently on vacation, I will test Steam as soon as I get home.

**Comment by flocke** [comment]
The 5 digits are not the real problem. This is just one line of code to change.
But they also use letters in their code, so it's not a 'real' TOTP. I will have to look into how it is generated and decide then if I want to implement it.
Since I'm currently on vacation this will take some time.

**Comment by Roliga** [comment]
Sounds good, thanks for your work on this app and have a great vacation!

**Comment by flocke** [comment]
After looking at the code for the KeeTrayTOTP plugin this seems very doable.
I will try to get this in for the next release.

**Comment by flocke** [comment]
I have an implementation to generate SteamGuard codes, but I'm not sure if I should release it for the following two reasons:

 1) You still have to get the secret somewhere and manually add it (I won't implement an automatic method where you just have to enter your steam account since this is far beyond the scope of this app).
 2) And after you activate it somehow you won't be able to trade in Steam anymore, since that requires confirmations that are handled by the Steam app.

**Comment by Roliga** [comment]
While I personally still would find this a very useful feature, the reasons you mentioned definitely means it's not for everyone. The use cases I see are:

* Using F-Droid as a primary app repository, where keeping the Steam app installed can be inconvenient.
* Having all 2FA codes in one place, making them easier to manage and securely back up.
* Having Steams authentication codes available on multiple devices. In this case, depending on how you acquire the secret, you could still use the normal Steam app as usual for trading.

While I don't use Steams trading functionality myself, and I'm sure I'm not the only one who doesn't, I imagine a lot of people indeed do. And as you say having to get the secret somehow manually isn't ideal either.

Either way I really appreciate your work on this app and the time you've spent on this feature!

**Comment by flocke** [comment]
This won't make it into the next release, I have to think about it a little bit more.
Maybe I will add it in the one after as a hidden option for people who know what they are doing.

**Comment by flocke** [comment]
I added this as an hidden option.
To enable it go to About and tap the version tile 7 times (stolen from dev options in Android).
There will be a warning that this is not further supported and you have to get the shared secret on your own.

**Disclaimer**: Steam trading won't work with this enabled since you won't be able to confirm trades.
This will never be implemented, so please nobody ask for it, this is far beyond the scope of this app!

**Comment by flocke** [comment]
I will publish the next release in a week, giving the translators time to catch up.
I wrote a little page about the hidden feature in the wiki: https://github.com/flocke/andOTP/wiki/Hidden-features
There you can also see how you can get your shared secret.

**Comment by Roliga** [comment]
Thanks for implementing this, much appreciated!

**Comment by theo546** [comment]
Hi, i give a feedback if needed, it work perfectly fine!!
for anybody that are on linux and want to convert the base64 code to base32, use this easy command (dont remove the quote!!):
echo "< code goes here >" | base64 -d | base32

**Comment by flocke** [comment]
@theo546 Thanks for the feedback and the command, I added it to the wiki page.

**Comment by mig4ng** [comment]
I activated the special features but where do I insert the secret to generate steam codes aswell?

**Comment by Roliga** [comment]
@mig4ng In andOTP press the **+** icon, then press **enter details**. Set **Type** to *STEAM*, set **Label** to whatever you want and put the secret you got in the **Secret** field.

I think the wiki mentions this [here](https://github.com/andOTP/andOTP/wiki/Special-features), but maybe it's not super clear (:

**Comment by mig4ng** [comment]
Thanks! Hope it helps others find it as well :)

**Comment by Kreyren** [comment]
ping @flocke: i have problems with Steam Authentificator on https://github.com/Winetricks/winetricks/pull/1371/files/eeb887a97ac0ee17eae5c2bef41185a93ffd2d3f

Did you find a way to get the hash so that the authentificator could be set up locally?

**Comment by theAkito** [comment]
This is absolutely amazing! Thank you for making my phone free of this Steam Guard bloatware. Thank you so much!
