### ISSUE TITLE
[question] encryption details

### ISSUE THREAD

**Issue by paolostivanin** [flocke/andOTP#39]
Hello,
I'm implementing a GTK+ OTP client for GNU/Linux and I would like to add support to import andOTP *encrypted* backup files.
Looking into the [source code](https://github.com/flocke/andOTP/blob/master/app/src/main/java/org/shadowice/flocke/andotp/Utilities/EncryptionHelper.java#L48), I saw that you are using AES128 GCM with a 12 bytes IV.
So the final encrypted file struct is `IV+ENC_TEXT+TAG`, right? And what about the key? It seems that it [is not entirely](https://github.com/flocke/andOTP/blob/master/app/src/main/java/org/shadowice/flocke/andotp/Utilities/EncryptionHelper.java#L95) user provided, so things here are getting complicated. Or am I missing something?

Thanks :)

**Comment by flocke** [comment]
You are right about the encrypted file structure. There is a python script for decrypting the backups already: https://github.com/asmw/andOTP-decrypt maybe this can help you better understand the format.
The key for the encryption is completely user-provided, it is generated using a SHA256 hash of the user-provided password and the IV.

**Comment by flocke** [comment]
The genKeyFromPassword function is used for the backups, the loadOrGenerateKeys function is only for the internal data store and has nothing to do with the backups.

**Comment by paolostivanin** [comment]
you're right, thanks :)
