### ISSUE TITLE
can not select a OpenPGP key 

### ISSUE THREAD

**Issue by red1ight** [flocke/andOTP#40]
I can not select a OpenPGP key from OpenKeychain (all version app from F-droid)
Meizu Pro5, Android 5.1 stock 
Also in OpenKeychain is no andOTP in the list of applications
But everything is good on BQ Aquaris M10 FHD with Android 5.1 stock

**Comment by flocke** [comment]
Currently only a private key can be used in andOTP, so make sure you have a private key available in OpenKeychain.

**Comment by red1ight** [comment]
yes, i have a private key available in OpenKeychain

**Comment by flocke** [comment]
OK, could you try and get a logcat for me. Without it I can not do anything to debug this problem.
Also I'm currently on vacation so it will take some time until I get to work on andOTP again.

**Comment by red1ight** [comment]
``

**Comment by red1ight** [comment]
`E/OpenPgp API(29508): exception on binding!
E/OpenPgp API(29508): java.lang.Exception: bindService() returned false!
E/OpenPgp API(29508): 	at org.openintents.openpgp.util.OpenPgpServiceConnection.bindToService(OpenPgpServiceConnection.java:105)
E/OpenPgp API(29508): 	at org.openintents.openpgp.util.OpenPgpKeyPreference.onClick(OpenPgpKeyPreference.java:92)
E/OpenPgp API(29508): 	at android.preference.Preference.performClick(Preference.java:1006)
E/OpenPgp API(29508): 	at android.preference.PreferenceScreen.onItemClick(PreferenceScreen.java:225)
E/OpenPgp API(29508): 	at android.widget.AdapterView.performItemClick(AdapterView.java:305)
E/OpenPgp API(29508): 	at android.widget.AbsListView.performItemClick(AbsListView.java:1222)
E/OpenPgp API(29508): 	at android.widget.AbsListView$PerformClick.run(AbsListView.java:3201)
E/OpenPgp API(29508): 	at android.widget.AbsListView$3.run(AbsListView.java:4056)
E/OpenPgp API(29508): 	at android.os.Handler.handleCallback(Handler.java:739)
E/OpenPgp API(29508): 	at android.os.Handler.dispatchMessage(Handler.java:95)
E/OpenPgp API(29508): 	at android.os.Looper.loop(Looper.java:135)
E/OpenPgp API(29508): 	at android.app.ActivityThread.main(ActivityThread.java:5574)
E/OpenPgp API(29508): 	at java.lang.reflect.Method.invoke(Native Method)
E/OpenPgp API(29508): 	at java.lang.reflect.Method.invoke(Method.java:372)
E/OpenPgp API(29508): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:962)
E/OpenPgp API(29508): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:757)
W/Interception( 2811): isInterceptByRule realCallingPid: 29508 isInterceptAsUsual: true isMatch: false, runType===retrieve_service|||callerPkg===org.shadowice.flocke.andotp|||calleePkg===org.sufficientlysecure.keychain|||calleeClass===org.sufficientlysecure.keychain.remote.OpenPgpService2|||processName===org.sufficientlysecure.keychain:remote_api_2|||action===org.openintents.openpgp.IOpenPgpService2|||data===*|||extras===*|||interception===false`

**Comment by red1ight** [comment]
Hmm. he earned! After I allowed the work in the background

**Comment by flocke** [comment]
Yeah, the log looked like he couldn't find the OpenKeychain service. Allowing it to run in the background should help.

**Comment by red1ight** [comment]
your apps is the best)

**Comment by flocke** [comment]
Thank you ;)
