### ISSUE TITLE
andOTP (F-Droid) on LineageOS: all tokens lost after update of LineageOS

### ISSUE THREAD

**Issue by gunnersson** [flocke/andOTP#45]
Dear all,

### my system:
* Motorola Moto G3 https://en.wikipedia.org/wiki/Moto_G_(3rd_generation)
* LineageOS as a replacement for stock Android https://download.lineageos.org/osprey
* andOTP 0.2.6 https://f-droid.org/packages/org.shadowice.flocke.andotp/
* before: lineage-14.1-20170914-nightly-osprey-signed.zip 2017-09-14 18:38:33
* after: lineage-14.1-20170921-nightly-osprey-signed.zip 2017-09-21 12:23:08
* no such thing like root/SuperUser/SU

### issue:
* after update of LineageOS all tokens are lost within andOTP (as seen in GUI)
* I do have a backup otp_accounts.json.aes
* but when trying to import: no question for password
* tokens not restored (as seen in GUI)

### maybe similar issue:
* https://github.com/flocke/andOTP/issues/16

### actions taken so far:
* actually none
* waiting for questions

Thank you for any help!

Kind regards,

Gunner

**Comment by flocke** [comment]
I assume you dirty-flashed the update.
Did you wipe the cache? If yes this is the reason, it should delete the Keystore entries so you can't decrypt the accounts anymore.

Try clearing the app data and then re-import the backup.
You have to set the password in the settings before importing, you won't be asked.

**Comment by gunnersson** [comment]
> I assume you dirty-flashed the update.

What does "dirty-flashed" mean? Sorry, but I just don't know that expression.

Well, I don't use the LineageOS built-in updater, but instead I manually copy the ZIP on the device and install it by using TWRP recovery then.

> Did you wipe the cache?

With TWRP, after installing a ZIP I always wipe cache and dalvik.

> Try clearing the app data and then re-import the backup.

Yes, I did. It was successfull. @flocke Thank you!

> You have to set the password in the settings before importing, you won't be asked.

Maybe this should be made more clear and labelled more precisely in GUI. Just a suggestion. (Thank you for your hint!)

@flocke Thank you!

**Comment by gunnersson** [comment]
Oh, because of my interest:

So this behaviour as described here is actually intended?

**Comment by flocke** [comment]
Glad you could solve it.

It's not really intended by me, but wiping the cache sadly always deletes the KeyStore entries, I can't do anything about it since this is a Android function.

"dirty-flashing" means that you install the new ZIP over the old one without factory-resetting the partitions.

**Comment by carmebar** [comment]
Documentation should be updated to note this behavior.

I had to reinstall the app. It said that the import was successful but no entries were added to the list.

**Comment by MartinX3** [comment]
Same Problem here.
Motorola Nexus 6 with LineageOS 14.1-20171013-NIGHTLY-shamu
Installed from Google Play

Is it possible to not use the KeyStore and only protect the keys with my password/pin/gesture?
That option would be nice.
I hate it to loose 8 tokens.

**Comment by flocke** [comment]
@MartinX3 I already thought about the idea to add an option to disable using the KeyStore and instead use the password/PIN for encryption. This however requires a major rewrite of the storage related stuff and will take some time.

**Comment by MartinX3** [comment]
Thank you very much, that you do it in the future.
Or another one with time to help you. :)

**Comment by flocke** [comment]
The problem with using the password for encryption is that I also need to store the password securely.
And the best way to do that is to use the KeyStore as well to encrypt the password so we would still be using the KeyStore ...

**Comment by MartinX3** [comment]
Couldn't you store the PW and another place?
Salted and Hashed?
Or give the ability to use the own GPG Key to secure the app?

Is the password for the device encryption at another place?
Because this doesn't change with an ROM reinstall.

**Comment by flocke** [comment]
I have to think about a good way to solve that problem.
Maybe I can come up with a solution without using the KeyStore.

**Comment by MartinX3** [comment]
Maybe the way the Apps "Threema and Signal" doing this may help you.

https://github.com/WhisperSystems/Signal-Android
https://threema.ch/en
