### ISSUE TITLE
Black Theme

### ISSUE THREAD

**Issue by mcR00T** [flocke/andOTP#47]
a black theme would make the app perfect for me (and my OnePlus 3 with an OLED screen)
thanks

**Comment by flocke** [comment]
Still thinking about how to do this the best ...
Just changing the background color to black is fairly easy, but if you have a few accounts added then you have more cards (gray) than background (black) which would be unfavorable for an OLED screen.

**Comment by mcR00T** [comment]
i think that the cards should also be black (so yeah no card layout visible)

**Comment by flocke** [comment]
I'm gonna test it and see how it looks ;)

**Comment by flocke** [comment]
I added a simple black theme, the window background and the card background are black (so there are effectively no cards).
All the popups and menus are still gray (since they are only shown on user-interaction this should not impact battery on OLED screens).

**Comment by flocke** [comment]
Ok, my current implementation seems to break Lollipop and below ... reopening to keep track
