### ISSUE TITLE
Can't import Backup

### ISSUE THREAD

**Issue by Ennneerrrgggyyy** [flocke/andOTP#48]
Hi,

first of all: great app! Thank you very much.

But I'm having trouble importing a backup. I keep getting the following message:
"Import vom externen Speicher fehlgeschlagen"

**Comment by flocke** [comment]
I'm gonna need some more information:

1. Which Android version are you using (and if you use a custom ROM, which one)?
2. What kind of backup are you using (plain, password or OpenPGP)?
3. **Most importantly**: I need a logcat or else I can't debug at all.

**Comment by Ennneerrrgggyyy** [comment]
Sorry, I can't replicate the error. I'll close the ticket!

Once again: Awesome app! :)
