### ISSUE TITLE
Authentication bypass via panic app

### ISSUE THREAD

**Issue by SpotComms** [flocke/andOTP#50]
On the latest 0.2.7 version from F-Droid having both an authentication method enabled combined with the "Reset app settings" panic trigger, results in bypassing the password/pin prompt after triggering a panic.

Steps to reproduce
- Install app
- Set 'Authentication' to "Device credentials" (or any other)
- Set 'Panic Trigger' to "Reset app settings"
- Add some tokens
- Exit app
- Open app to confirm that its locked and exit again
- Open panic app (eg. Ripple) and trigger a panic
- Open andOTP
- See keys without having to enter password/pin

Ways to fix
- [clear()](https://github.com/flocke/andOTP/commit/247f4e938ed6def7668e3259c81a6fc9e1dd5db0#diff-db821fc78f1767243d1038deacbcd954R85) needs to be amended to not reset the settings for Authentication
- or simply remove the "Reset app settings choice", although "Wipe all accounts" is pretty aggressive, simply locking the app should be the default

**Comment by flocke** [comment]
I don't think that wiping the the settings is really useful at all. For now all that can be read from the settings is the password for the authentication and the backups. But I plan to store that hashed and with this unrecoverable in the future. After that wiping the settings won't be useful anymore and I will remove it altogether. After that the only option will be to wipe all accounts, which is of course extreme but it's totally optional.

**Comment by flocke** [comment]
I amended clear() to keep the authentication-related settings.
Maybe later on I will add a third option to the panic reactions to lock the app even if it is unlocked.
