### ISSUE TITLE
How do I set the app with Google's 2 factor authentication?

### ISSUE THREAD

**Issue by doronbehar** [flocke/andOTP#51]
#### General information

* **App version:** 0.2.7
* **App source:** F-Droid
* **Android Version:** 7.1.2 LineageOS (no GAPPS)

**Comment by flocke** [comment]
I never tried it myself (I use Gapps and the Google Prompt) so I can't answer this, maybe someone else can answer you.

**Comment by flocke** [comment]
I just tried it ... you just have to scan the QR code when you enable 2FA in your Google account settings: https://myaccount.google.com/signinoptions/two-step-verification

**Comment by doronbehar** [comment]
Great, it worked. Perhaps we should add it to the README..

**Comment by flocke** [comment]
Glad it worked.
I'm not gonna add it to the README, if I do then people are gonna start asking how to set up site xyz with the app and I really want to avoid that ;)
