### ISSUE TITLE
Turn on Documents error when creating backup

### ISSUE THREAD

**Issue by TeddyDD** [flocke/andOTP#52]
#### General information

* **App version:** 0.2.7
* **App source:** Google Play
* **Android Version:** 5.0.2

#### Expected result
I expect that after I click Backup (both plain text and OpenPGP) app will create file somewhere and tell me where is that file.

Instead "Turn on Documents in Settings > Installed apps first" popup appears.
I don't have such option in settings, all permissions are turned on. 

#### Logcat
I tried to get log specific to this app using following command `adb -d logcat 'org.shadowice.flocke.andotp:E'` but it was massive spam. I'm not Android dev, I'd be grateful for hints how to get useful logs. Anyway here is raw logcat dump I created following linked instruction: [Gist](https://gist.github.com/TeddyDD/80fbe8389378f104b6a5fa05e17ea97f)

#### Steps to reproduce
 
 * click Backup > Backup (plain text) or Backup (OpenPGP)

**Comment by flocke** [comment]
Seems like you don't have any App installed that can handle the `ACTION_CREATE_DOCUMENT` intent, which would ask you where to save the backup. Normally this should be handled by the stock Android Document UI.
Are you using a custom ROM? If yes which one?

**Comment by TeddyDD** [comment]
I'm using MIUI 9 (xiaomi.eu). I did quick search and it seems that it's common issue with MIUI. Unfortunetly I can't apply [this](http://en.miui.com/thread-251046-1-1.html) fix since I don't have Documents app at all. Is there any app in Google Play or FDroid I could install to be replacement to Android Document UI?

**Comment by flocke** [comment]
Sadly I don't know of any app that could replace documents.
If it's a known issue maybe someone in the MIUI forums can help you.

**Comment by TeddyDD** [comment]
Sure, I'll look into it. Anyway It would be nice if app could just save backup somewhere (fallback method).

**Comment by flocke** [comment]
Sure, that would be the best solution.
I will try to get something like that in for the next release.

**Comment by flocke** [comment]
Since it is not that easy to automatically detect if you have the Documents app installed or not I just added a option to the settings to disable the file selector.
You can additionally specify a directory where the backups will be saved (the filenames are static and depend on the backup type).
This will be included in the next release.
