### ISSUE TITLE
Importing Google authenticator data? 

### ISSUE THREAD

**Issue by 5t0rmr1d3r** [flocke/andOTP#54]
Is there a way to import the Google authenticator data?

**Comment by puddly** [comment]
@5t0rmr1d3r Google Authenticator doesn't allow you to export the tokens. If your phone is rooted, you can read them out of the Google Authenticator database. I just had the same issue and wrote [this Python script](https://gist.github.com/puddly/7a1225e927a80ecb6325a43210ae77be) to export Authy and Google Authenticator tokens if your phone is rooted.

@flocke I don't know enough about Android development to make a pull request implementing the changes (or if the Google Play Store would even allow them), but it'd be really useful if you can implement importing tokens from other apps for rooted devices. Authy and Google Authenticator don't do anything complicated to store their tokens.

**Comment by flocke** [comment]
@puddly I don't want to start adding root functions to andOTP. It should stay as simple and light as possible.
What would be possible is to adapt your script so it generates a JSON file from the accounts which then can be imported into andOTP as plaintext backup.

**Comment by 5t0rmr1d3r** [comment]
@puddly thank you! I'll try that!

**Comment by 5t0rmr1d3r** [comment]
@flocke that would be even more comfortable!

**Comment by flocke** [comment]
If you update your script take a look at #55, the secrets should always be upper-case.

**Comment by 5t0rmr1d3r** [comment]
Thanks for the hint!
As soon as i had known that it's sqlite db the easiest way was to use an sqlite browser to export the data and then to uppercsse the secrets with notepad++.
After that i converted it manually to the json import format.

**Comment by 5t0rmr1d3r** [comment]
After closing this issue maybe an wiki page for other users would be helpful?

**Comment by puddly** [comment]
@flocke I understand. I've updated my code to generate AndOTP backup files and moved it to a dedicated repo ([android-otp-extractor](https://github.com/puddly/android-otp-extractor)) if you want to add it to a wiki page.

Personally, I prefer the QR codes because they're faster to scan and more secure than moving the backup JSON file to my phone, work with other OTP apps, and don't overwrite your existing accounts (unlike the backup).

**Comment by flocke** [comment]
@puddly Thank you, I will add it as soon as I get back home.

Yeah, I understand why you prefer QR codes, but if you got a lot of accounts the JSON file might be the better option. If have it on my TODO list to add an option to the backup to not overwrite all accounts but to append them.

**Comment by flocke** [comment]
@puddly I added your script to the wiki: https://github.com/flocke/andOTP/wiki/Migration
