### ISSUE TITLE
Case sensitive secrets

### ISSUE THREAD

**Issue by nazar-pc** [flocke/andOTP#55]
#### General information
* **App version:** 0.2.7
* **App source:** F-Droid
* **Android Version:** 7.1.2 (LineageOS 14.1)

I was migrating from Google Autenticator, so I've copied its sqlite database from /data/data/** and created `otp_accounts.json` file in the format andOTP expects. However, only those secrets that were in uppercase generated the same codes as Google Authenticator, those that were lowercase generated wrong codes. As soon as I've converted all lowercase secrets to uppercase, they've all started to generate correct codes.

Following generates wrong codes:
```
{"secret":"xyz","label":"user@gmail.com","period":30,"digits":6,"type":"TOTP","algorithm":"SHA1"}
```
Following generates correct codes:
```
{"secret":"XYZ","label":"user@gmail.com","period":30,"digits":6,"type":"TOTP","algorithm":"SHA1"}
```

I haven't read the spec whether these codes should always be uppercase, but looks like they should.

I think this is something that can/should be fixed (converted to uppercase on backup restoration), but feel free to close this if it is not relevant.

**Comment by flocke** [comment]
To be honest I never encountered lower-case secrets. Usually they should be encoded as [Base32](https://en.wikipedia.org/wiki/Base32)-String which should always be upper case.
I will add a conversion to upper-case when importing accounts.

**Comment by flocke** [comment]
Import from JSON was literally the only case where I forgot the conversion to upper-case.
When manually adding an entry or scanning a QR code the secret is always converted to upper-case.
@nazar-pc Thanks for finding this bug ;)

**Comment by nazar-pc** [comment]
Thanks for fixing this issue and for the app!
