### ISSUE TITLE
[French translation] Visual bugs

### ISSUE THREAD

**Issue by dsferruzza** [flocke/andOTP#58]
Hi!

I fixed a lot of mistakes in the French translation, and discovered a few display bugs:

\# | File | String | Bug
---|---|---|---
1 | strings_about.xml | [Help to translate andOTP to your language](https://crowdin.com/translate/andotp/18/en-fr#338) | Truncated after "votre"
2 | strings_about.xml | [Report bugs or request new features](https://crowdin.com/translate/andotp/18/en-fr#245) | Truncated after "demander de"
3 | strings_main.xml | [Digits](https://crowdin.com/translate/andotp/20/en-fr#373) | Truncated. We can only read "Nombre de". Then there is a line break and "chiffres" is hidden

Screenshots are blocked by the app for the screen were translation 3 appears, but here is a screenshot where you can see translations 1 and 2:

![screenshot_20171102-114018_01](https://user-images.githubusercontent.com/1931963/32338974-52bf74de-bfc4-11e7-9d0e-93bc954b9fe2.jpg)

Let me know if I can do something more!

**Comment by flocke** [comment]
@dsferruzza  I tried to fix the problems and it worked well on my phone. Hopefully this also works on other screen sizes.
I will close this issue for now, feel free to re-open it at any time if something like this comes up again.
