### ISSUE TITLE
Auto login after entering correct PIN/PASSWORD

### ISSUE THREAD

**Issue by jerryn70** [flocke/andOTP#59]

**Comment by flocke** [comment]
How do you mean that?
Just removing the need to press enter after entering the PIN/password and automatically unlock?

**Comment by jerryn70** [comment]
Yes

**Comment by flocke** [comment]
I'm currently reworking how the login passwords are stored (improving security a bit further than just using a simple SHA256 hash). After that is done I will look into your request.

**Comment by flocke** [comment]
The way I currently plan to implement the password storage (and eventually password-based encryption of the data files as an alternative to the KeyStore, see [this wiki entry](https://github.com/flocke/andOTP/wiki/%5BProposal%5D-Improved-encryption)) this would indeed require me to store the password length separately and unencrypted.
I don't think we should give potential attackers that additional hint, so I won't be implementing this.
