### ISSUE TITLE
[Poll] App name inaccurate in some places

### ISSUE THREAD

**Issue by ageru** [flocke/andOTP#6]
# Help wanted: Please head down to the poll and vote for a name for the andOTP launcher icon

Android 7.1.1
andOTP 0.22

## Steps to reproduce
1) Install app from F-droid

## Actual result
App name is 'OTP Authenticator' in app drawer/Android Home, and in the main screen of the app. App is named 'andOTP' accurately in the about section of the app and in Settings>Apps

## Expected result
App name should be 'andOTP' in every instance

**Comment by flocke** [comment]
This is intended, I wanted the Launcher icon to be named "OTP Authenticator".
Maybe this is confusing some people, if so I can change it.
Let's wait for some more opinions.

**Comment by flocke** [comment]
Here is a poll to see what the users prefere as name in the launcher:

[![](https://m131jyck4m.execute-api.us-west-2.amazonaws.com/prod/poll/01BNWRAS1MQ5581F32VEG8Q3RZ/OTP%20Authenticator)](https://m131jyck4m.execute-api.us-west-2.amazonaws.com/prod/poll/01BNWRAS1MQ5581F32VEG8Q3RZ/OTP%20Authenticator/vote)
[![](https://m131jyck4m.execute-api.us-west-2.amazonaws.com/prod/poll/01BNWRAS1MQ5581F32VEG8Q3RZ/andOTP)](https://m131jyck4m.execute-api.us-west-2.amazonaws.com/prod/poll/01BNWRAS1MQ5581F32VEG8Q3RZ/andOTP/vote)

**Comment by flocke** [comment]
Ok, seems pretty obvious where the poll is going.
I changed the names to "andOTP", will be in the next release.

**Comment by jerryn70** [comment]
Why you choose the name andOTP ? Any reason behind this ? 

I didn't mind the name changes in the app drawer and in the settings. But you guys are right some users get confused of this. 

My opinion is, the name 'andOTP' is not good/attractive/catching. Dont be sad, i know this is your first project , iam just telling what I feel that's all. I know it's hard to change the name of the app, so don't take my words as serious. 
You are the owner of this app you have the right to choose which name should appear on app drawer and settings. Do what your mind says . 👍

**Comment by flocke** [comment]
No specific reason for the name. I just needed something to call my fork and I'm not very creative when it comes to those things ;)

Changing the name now that it is deployed on both Google Play and F-Droid would be a bit complicated (and would require an idea for a new name ...), so I'm just gonna stick with andOTP.
