### ISSUE TITLE
[Feature Request] Support saving backups in UriKey format

### ISSUE THREAD

**Issue by RichyHBM** [flocke/andOTP#62]
It would be great if andOTP had the ability to save backups in the UriKey format, this would make it compatible with tools like WinAuth.

**Comment by flocke** [comment]
I saw you already send a pull request for that feature. But to be honest I am still on the fence about implementing this. I want to keep andOTP as light as possible and don't want to start adding import and export functions to make it compatible with every other 2FA app out there.
Let me think about it a bit more when I get home on monday.

**Comment by RichyHBM** [comment]
Sure, thats fine! That said, I feel like UriKey is more of a standard format for authenticators, though I completely agree that we shouldn't just add features to support exporting to a particular authenticator!

**Comment by flocke** [comment]
Yes, but im my opinion the best solution would be the same we use for importing from other authenticators: have a script that converts the exported JSON file to UriKey format afterwards.

**Comment by flocke** [comment]
After thinking some more about this I won't be implementing this feature.

While I can see why you would want this feature the export function is only intended to be a backup for andOTP itself and not an export to be imported by other apps. Additionally it should be fairly easy to just write a script that takes the JSON backup files and converts them to the UriKey format, which is basically the same way we handle imports from other apps (https://github.com/flocke/andOTP/wiki/Migration).
