### ISSUE TITLE
Device Authentication Asked Again After Configuration Change

### ISSUE THREAD

**Issue by commonsguy** [flocke/andOTP#7]
Version: 0.2.2

Steps to Reproduce:

1. In Settings, check "Require device credentials"

2. Swipe the app off the overview screen, so you start from a clean slate

3. Restart the app from the home screen, and authenticate against the device

4. Rotate the screen

Expected Results: Nothing out of the ordinary

Actual Results: You have to authenticate again

----

Right now, you execute [these lines](https://github.com/flocke/andOTP/blob/v0.2.2/app/src/main/java/org/shadowice/flocke/andotp/MainActivity.java#L135-L144) for every `onCreate()` of `MainActivity`. Hence, on a configuration change, we have to re-authenticate, which IMHO is aggravating.

Some options for addressing this:

- Only execute that code if `savedInstanceState` is `null`. This requires re-authentication after the task expires (~30 minutes or until manually removed from the overview screen).

- Use `onRetainNonConfigurationInstance`, the Architecture Components' `ViewModel` stuff, or a retained fragment to retain your view model (entries data, a have-we-authenticated `boolean`, etc.) across configuration changes, retrieving it in `onCreate()` via `getLastNonConfigurationInstance()`, and only re-authenticate if we need to load the data again

- Block configuration changes in the manifest via `android:configChanges` on the `<activity>` element. Personally, I don't recommend this option.

- Say that this behavior is working as intended. :-)

**Comment by flocke** [comment]
This is definitely not intended.
I will look into it, thanks for your suggestions.

**Comment by flocke** [comment]
I used the `savedInstanceState == null` methode, which seems to work well for me.
