### ISSUE TITLE
Version 0.3 seems to be Version 0.2.8

### ISSUE THREAD

**Issue by stonerl** [flocke/andOTP#72]
Something seems to be wrong with the version numbering. The apk says 0.3 but on the app it says 0.2.8 also when you go to system settings.

The day 0.3 got released the f-droid repo git updated but it still shows the old version.

**Comment by flocke** [comment]
Which APK are you talking about, the one here on Github or the one on F-Droid?

**Comment by stonerl** [comment]
The one here on github

**Comment by flocke** [comment]
Strange, I will check when I get home tomorrow. Could be I uploaded the wrong version.

**Comment by flocke** [comment]
Are you sure you downloaded the correct version?
I just downloaded the v0.3.0 APK from Github and it is indeed version 0.3.0.

**Comment by stonerl** [comment]
I used this link:
https://github.com/flocke/andOTP/releases/download/v0.3.0/andOTP_v0.3.0.apk

This is the files md5:
a013052f64befa3197f5425787efabb8

But this version is shown:

![screenshot_20171126-140912](https://user-images.githubusercontent.com/2091312/33283474-37112114-d3ac-11e7-8014-57cf96b8b8d5.png)

![screenshot_20171126-140855](https://user-images.githubusercontent.com/2091312/33283483-3f435014-d3ac-11e7-917d-6862ce9040c7.png)

Maybe you just forgot to update the Version string?

**Comment by flocke** [comment]
Nope, I just installed the same APK file from Github on my device and it says 0.3.0.
Did you try to upgrade from the F-Droid version? If yes you have to uninstall the F-Droid version first (don't forget the backup!!!) and install the APK afterwards.
They are signed with different keys, so installing one "over" the other doesn't work.

**Comment by stonerl** [comment]
I'm stupid... Sorry for the fuz. Just uninstalled it and installed it again. Don't know why but for some reason the package installer did not give me an error and I assumed it had been installed. Should have checked twice before filing a (non) bug. Sorry.

**Comment by flocke** [comment]
No worries, I am glad it worked itself out.
Strange though that there was no error.
